version: "3.8"
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    environment:
      # ホストを127.0.0.1に設定して外部からの直接アクセスを防ぐ
      - HOST=127.0.0.1
      # Microsoft OAuth設定
      - ENABLE_OAUTH_SIGNUP=true
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - MICROSOFT_CLIENT_TENANT_ID=${MICROSOFT_CLIENT_TENANT_ID}
      # 通常のログインを無効化する設定
      - ENABLE_SIGNUP=false
    volumes:
      - open-webui-data:/app/backend/data
    ports:
      - "127.0.0.1:8080:8080"  # ローカルホストのみで公開

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel run

volumes:
  open-webui-data:
