version: "3.8"
services:
  open-webui:
    build: .
    image: custom-open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    environment:
      # Cloudflareトンネルからアクセスできるようにホストを0.0.0.0に設定
      - HOST=0.0.0.0
      # Microsoft OAuth設定
      - ENABLE_OAUTH_SIGNUP=true
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - MICROSOFT_CLIENT_TENANT_ID=${MICROSOFT_CLIENT_TENANT_ID}
      # 通常のログインを無効化する設定
      - ENABLE_SIGNUP=false
      - ENABLE_LOGIN_FORM=false
      - ENABLE_PASSWORD_LOGIN=false
    volumes:
      - open-webui-data:/app/backend/data
    ports:
      - "8080:8080"  # Cloudflareトンネルからアクセスできるように公開

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel run

volumes:
  open-webui-data:
