# バージョン属性は非推奨のため削除
services:
  open-webui:
    build:
      context: .
      args:
        # メモリ不足対策
        NODE_OPTIONS: --max-old-space-size=4096
        DOCKER_BUILDKIT: 1
      dockerfile: Dockerfile
      # ビルドプロセスを最適化
      shm_size: '2gb'

    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY='
      # アプリケーション名の設定
      - WEBUI_NAME=Revol GPT
      # Microsoft OAuth設定
      - ENABLE_OAUTH_SIGNUP=true
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - MICROSOFT_CLIENT_TENANT_ID=${MICROSOFT_CLIENT_TENANT_ID}
      # 通常のログインを無効化する設定
      - ENABLE_SIGNUP=false
      - ENABLE_LOGIN_FORM=false
      - ENABLE_PASSWORD_LOGIN=false
      # ホストを0.0.0.0に設定
      - HOST=0.0.0.0
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel run

volumes:
  open-webui: {}
